name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.408'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Blazor WebAssembly app
      run: dotnet publish -c Release -o release

    - name: Copy index.html to 404.html (for GitHub Pages SPA routing)
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./release/wwwroot
        publish_branch: gh-pages
